replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80

# Content for the index.html page for v2.0
htmlContent: |
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>SimpleWebApp v2.0 - Upgraded!</title>
      <style>
          body { font-family: sans-serif; background-color: #90EE90; /* Light Green */ text-align: center; padding-top: 50px; }
          h1 { color: #006400; /* Dark Green */ }
          p { font-size: 1.2em; }
          .version-info { margin-top: 20px; padding:10px; background-color: #FFFFE0; border: 1px solid #F0E68C;}
          .health { color: green; font-weight: bold; }
          .new-feature { background-color: #FFD700; padding: 10px; border: 1px solid #FFA500; margin-top:15px;}
      </style>
  </head>
  <body>
      <h1>Welcome to SimpleWebApp - Version 2.0 (Upgraded!)</h1>
      <p>This version includes exciting new features and improvements!</p>
      <div class="version-info">
          App Version: 2.0<br>
          DB Schema Mock: 2.0<br>
          DTA Component Mock: 2.0
      </div>
      <div class="new-feature">
          <h2>New Feature X Activated!</h2>
          <p>Our amazing new Feature X is now enabled thanks to the upgrade!</p>
      </div>
      <p class="health" id="healthStatus">Health Status: OK (Post-Upgrade)</p>
  </body>
  </html>
