apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simplewebapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "simplewebapp.name" . }}
    helm.sh/chart: {{ include "simplewebapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "simplewebapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "simplewebapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe: # Basic probe
            httpGet:
              path: /index.html
              port: http
          readinessProbe: # Basic probe
            httpGet:
              path: /index.html
              port: http
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html # Nginx default serve path
              subPath: index.html
      volumes:
        - name: html-volume
          configMap:
            name: {{ .Release.Name }}-html-config